name: Build and Deployment

on:
  push:
    branches:
      - main
    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.generate-env.outputs.ENVIRONMENT }}
      APP_NAME: ${{ steps.repo-name.outputs.repository-name }}
      IMAGE_TAG_NGINX: nginx-${{ steps.generate-env.outputs.ENVIRONMENT }}-${{ github.run_number }}
      IMAGE_TAG_APP: app-${{ steps.generate-env.outputs.ENVIRONMENT }}-${{ github.run_number }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'semilore'
          environment_name: 'Semilore-env'
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: target/soft-0.0.1-SNAPSHOT.jar